alias:
  default: &default
    working_directory: /tmp/orchis
    docker:
      - image: circleci/clojure:lein-node
        environment:
          GITHUB_API: "https://api.github.com/"
          OWNER_NAME: "rinx"
          REPO_NAME: "orchis"
          DOCKER_USER: "rinx"
          DOCKER_REPO_NAME: "rinx"
          IMAGE_NAME: "orchis"
  setup_remote_docker: &setup_remote_docker
    version: 18.06.0-ce
    docker_layer_caching: true

version: 2
jobs:
  build:
    <<: *default
    steps:
      - setup_remote_docker: *setup_remote_docker
      - checkout
      - run:
          name: check docker version
          command: |
            docker version
      - run:
          name: docker image build
          command: |
            # env DOCKER_BUILDKIT=1 docker build -t ${DOCKER_REPO_NAME}/${IMAGE_NAME}:latest .
            docker build -t ${DOCKER_REPO_NAME}/${IMAGE_NAME}:latest .
      - run:
          name: save image
          command: |
            docker image save ${DOCKER_REPO_NAME}/${IMAGE_NAME}:latest > ./docker-image.tar
      - persist_to_workspace:
          root: .
          paths:
            - .
  publish_nightly:
    <<: *default
    steps:
      - setup_remote_docker: *setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: load image from tar
          command: |
            docker load -i ./docker-image.tar
      - run:
          name: tag to latest
          command: |
            docker tag ${DOCKER_REPO_NAME}/${IMAGE_NAME}:latest ${DOCKER_REPO_NAME}/${IMAGE_NAME}:nightly
      - run:
          name: docker login
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: push image to registory
          command: |
            docker push ${DOCKER_REPO_NAME}/${IMAGE_NAME}
  publish:
    <<: *default
    steps:
      - setup_remote_docker: *setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: load image from tar
          command: |
            docker load -i ./docker-image.tar
      - run:
          name: tag to latest
          command: |
            docker tag ${DOCKER_REPO_NAME}/${IMAGE_NAME}:latest ${DOCKER_REPO_NAME}/${IMAGE_NAME}:$CIRCLE_TAG
      - run:
          name: docker login
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          name: push image to registory
          command: |
            docker push ${REPO_NAME}/${IMAGE_NAME}
  versioning:
    <<: *default
    steps:
      - setup_remote_docker: *setup_remote_docker
      - checkout
      - run:
          name: semver-tag-push-release
          command: |
            NEW_VERSION=`docker run -v /tmp/orchis:/src -it rinx/orchis:latest semver-tag-push`
            echo $NEW_VERSION
            if [ -n $NEW_VERSION ]; then
              docker run -v /tmp/orchis:/src -it rinx/orchis:latest gh-release \
              --github-api-url=${GITHUB_API} --github-api-token=${GITHUB_TOKEN} \
              --github-owner=${OWNER_NAME} --github-repo=${REPO_NAME}
            fi

workflows:
  version: 2
  build:
    jobs:
      - build
      - publish_nightly:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - versioning:
          filters:
            branches:
              only:
                - master
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
