name: Build docker image
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and publish to the registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: rinx/orchis
        username: rinx
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        snapshot: true
        pull_requests: true
